---
title: "Hu moments for MNIST"
output: html_notebook
---

# Install readmnist

Unfortunately the MNIST dataset is not really helpful when you want to load it, so theres a package for that:

```{r, eval=F}
install.packages("readmnist")
install.packages("R.utils")
```

# Download the datasets

Run these in you computer's shell:

```{sh, eval = F}
curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
curl -O http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
curl -O http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
curl -O http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz

gunzip t*-ubyte.gz
```

Or:

```{r}
# download data from http://yann.lecun.com/exdb/mnist/
download.file("http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz",
              destfile = "../data/mnist/train-images-idx3-ubyte.gz")
download.file("http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz",
              destfile = "../data/mnist/train-labels-idx1-ubyte.gz")
download.file("http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz",
              destfile = "../data/mnist/t10k-images-idx3-ubyte.gz")
download.file("http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz",
              destfile = "../data/mnist/t10k-labels-idx1-ubyte.gz")

# gunzip the files
R.utils::gunzip("../data/mnist/train-images-idx3-ubyte.gz")
R.utils::gunzip("../data/mnist/train-labels-idx1-ubyte.gz")
R.utils::gunzip("../data/mnist/t10k-images-idx3-ubyte.gz")
R.utils::gunzip("../data/mnist/t10k-labels-idx1-ubyte.gz")
```


# Setup

```{r setup}
library(readmnist)
library(tidyverse)
library(rcell2)
```

# Load dataset

The training datasets:

```{r}
mnist.train <- readmnist::Read.mnist("../data/mnist/train-images-idx3-ubyte")
mnist.labels <- readmnist::Read.mnist("../data/mnist/train-labels-idx1-ubyte")
```

## Get one image

    pic 	the images from the dataset, and each row is one image.(if it's a image file)

```{r}
mnist.train$pic %>% dim()

mnist.train$pic[1,] %>% length() %>% sqrt()

mnist.labels$labels[3]

pic <- mnist.train$pic[3,]
```

## Render it

```{r}
matrix(pic, ncol = 28)
```


```{r}
# show_digit = function(arr784, col = gray(12:1 / 12), ...) {
#   image(matrix(as.matrix(arr784[-785]), nrow = 28)[, 28:1], col = col, ...)
# }
# 
# show_digit(pic)
```

```{r}
#Obtaining the row as a numeric vector
# r <- as.numeric(d[row_index, 2:785])
r <- pic

#Creating a empty matrix to use
im <- matrix(nrow = 28, ncol = 28)

#Filling properly the data into the matrix
j <- 1
for(i in 28:1){

  im[,i] <- r[j:(j+27)]

  j <- j+28

}  

#Plotting the image with the label
image(x = 1:28, 
      y = 1:28, 
      z = t(im), 
      col=gray((0:255)/255), 
      main = "mnist pic")
```



```{r}
pic.matrix <- matrix(pic, ncol = 28, nrow = 28, byrow = T)

heatmap(pic.matrix, Rowv = NA, Colv = NA, scale = "none")
heatmap(t(pic.matrix), Rowv = NA, Colv = NA, , scale = "none")
```

