---
title: "CellID Wrapper Test 3"
author: "Nicolás Méndez"
date: "7/20/2020"
output: html_document
---

# Rebuild

```{r build, message=FALSE, warning=TRUE}

devtools::document()
devtools::load_all(recompile = F, reset = T, quiet = T)
# devtools::install(reload = T, build = F,
#                   quiet = T,
#                   upgrade = "never", keep_source = T)
# devtools::install_github("gerbeldo/rcell2", ref = "rcellid_no_labels")
# devtools::check()
# devtools::build()
# devtools::build(path="../../test_libtiff.tar.gz")
# remove.packages("rcell2")
# install.packages("../../test_libtiff.tar.gz", repos = NULL, type="source", clean = TRUE)

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
# library(rcell2)

path <- "../data/image_samples/"
path.pdata <- paste0(path, "pdata.csv")
parameters <- "../inst/parameters.txt"

difference <- function(lista) abs(lista[1] - lista[2])
```

# USAGE 

```{r}
cell.data <- rcell2::cell.load.alt(path =  path, cellid.zero.pad = 5)

head(cell.data$d) %>% select(ucid, pos, cellID, t.frame)

#### SETUP PATHS DATAFRAME ####
paths <- rcell2::magickPaths(cell.data)

p <- cell.data$d %>% ggplot() + 
  geom_point(aes(x = a.tot, y = fft.stat, color = pos)) +
  theme(legend.position = "none")

p
```


```{r}
# devtools::document()
# devtools::load_all(recompile = F, reset = T, quiet = T)
# ?rcell2::tagCell
p <- ggplot(mapping = aes(x=t.frame, y=cf.y, group=ucid)) + 
  geom_line()

saved <- rcell2::tagCell(cell.data$d, pdata, paths, 
                         cell_tags = list(far1_drop = c(TRUE,
                                                        FALSE),
                                          artifact = c("segmentation",
                                                       "death")
                                          ),  # list(named_item1 = c(option1, option2, ...), named_item2 ...)
                         # t_frame_tile = "vertical",  # c("vertical", "horizontal", "animate", "stack")
                         # tag_channels_select = NULL,  # c("BF.out", "BF", "YFP", ...)
                         tag_box_size = 75,
                         tag_ggplot = p)


saved
```


```{r}
cell.data <- readRDS("~/Projects/Colman/gitlabs_acl/rtcc/far1/analisis_Far1_arresto-lavado/output/cell.data20200728_a20c377c8979.RDS")
image.paths <- rcell2::magickPaths(cell.data)
datos_splines <- readRDS("~/Projects/Colman/gitlabs_acl/rtcc/far1/analisis_Far1_arresto-lavado/output//datos_splines_20200902_1bd5862e36193.RDS")
cdata.filtered4 <- readRDS("~/Projects/Colman/gitlabs_acl/rtcc/far1/analisis_Far1_arresto-lavado/output/cdata.filtered4_20200814_9a43be8ccdb.RDS")
pdata <- readr::read_csv("~/Projects/Colman/gitlabs_acl/rtcc/far1/analisis_Far1_arresto-lavado/data/arresto-lavado/Pre_alphaF/2019_11_20_Exp_Ali.csv")
```


```{r}
p <- ggplot(cdata.filtered4) + 
  geom_line(aes(x=t.frame, y=cf.y, group=ucid))

p %+% arrange(cdata.filtered4, ucid)[1:10,]
```


```{r}
devtools::document()
devtools::load_all(recompile = F, reset = T, quiet = T)
saved <- rcell2::tagCell(cdata.filtered4,
                         pdata, image.paths,
                         cell_tags = list(far1_drop = c(TRUE,
                                                        FALSE),  # t.drop aparente pero falso por algun artefacto
                                          budding =   c("emergence",
                                                        "division"),
                                          artifact =  c("segmentation",
                                                        "out_of_focus",
                                                        "interesante",
                                                        "death",
                                                        "flown_away")
                                          ),  # list(named_item1 = c(option1, option2, ...), named_item2 ...)
                         # t_frame_tile = "vertical",  # c("vertical", "horizontal", "animate", "stack")
                         tag_channels_select = c("BF.out", "YFP"),  # c("BF.out", "BF", "YFP", ...)
                         n_max = 50,
                         tag_box_size = 75,
                         cell_resize = 300,
                         tag_ggplot = p)
```


```{r}
saved_data <- shinyCell(cell.data$d, pdata, paths,
                        plotType = "Dots",
                        # initial_facet = "pos ~ .",
                        #filters = saved_data$filters,
                        facet_grid_option = TRUE,
                        n_max = 7^2, max_size = 720)

# More plots would be useful
ggplot(data = subset(saved_data$cdata, filter == T)) +
  geom_boxplot(aes(y = cf.y, x = factor(pos)), width=0.1) +
  geom_violin(aes(y = cf.y, x = factor(pos), color = factor(pos)), alpha = 0) +
  theme_minimal()
```

