---
title: "CellID Wrapper Test 3"
author: "Nicolás Méndez"
date: "7/20/2020"
output: html_document
---

# Rebuild

```{r build, eval=FALSE, message=FALSE, warning=TRUE}
devtools::document()
devtools::load_all(recompile = T, reset = T)
devtools::install(reload = T, build = T,
                  quiet = T,
                  upgrade = "never", keep_source = T)
```


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rcell2)
```

# Ejemplo de uso con nuevo arguments2

### CellID parameters

Deshabilitar `align_individual_cells`, generaba artefactos en la fluorescencia de Far1.

```{r}
# parameters <- "~/Software/cellID-linux/test_data_tmp2/parameters_example2.txt"
# parameters <- "../data/time_series_image_samples_bf_as_fl/parameters.txt"
# parameters <- "/home/nicomic/Software/cellID-linux/test_data_andy/Position001/parameters_vcellid_out.txt"
parameters <- "../inst/parameters_test.txt"

param_array <- c(
  "max_split_over_minor 0.50",
  "max_dist_over_waist 8.00",
  "max_pixels_per_cell 2000",
  "min_pixels_per_cell 75",
  "background_reject_factor 0.5",
  "tracking_comparison 0.20",
  # "align_individual_cells",  # tambien se puede deshabilitar con un "#" en el mismo parameters.txt
  "align_fl_to_bf",
  "image_type brightfield",
  "bf_fl_mapping list")

write(param_array, file = parameters)
```

Imprimir contenidos del parameters.txt:

```{r}
writeLines(readLines(parameters))
```

### Generar arguments

```{r}
# path <- "~/Software/cellID-linux/test_data_tmp2/"
path <- "../data/image_samples/"
# path <- "../data/time_series_image_samples_bf_as_fl/"
# path <- "/home/nicomic/Software/cellID-linux/test_data_andy/"
# path <- "/home/nicomic/Software/cellID-linux/test_data_rtcc/"

arguments <- rcell2::cellArgs2(path = path, parameters = parameters, file.pattern = "^(BF|[A-Z]FP)_Position(\\d+)().tif$")

arguments
```

### Correr CellID

```{r}
rcell2::cell2(arguments = arguments, 
              cell.command = "~/Software/cellID-linux/cell",
              # cell.command = system.file("cell", package = "rcell2", mustWork = T),
              dry = T, no_cores = 1)
```


```{r}
rcell2::cell2(arguments = arguments, 
              cell.command = "~/Software/cellID-linux/cell", # cell.command = system.file("cell", package = "rcell2", mustWork = T),
              dry = F, no_cores = 1, label_cells_in_bf = T)
```

# Load cell data

```{r}
# cell.data.old <- rcell2::cell.load.alt(path =  path)
cell_data.new <- rcell2::load_cell_data(path = path)

cell_data.new$data %>% filter(cellID == 1003) %>% 
  rcell2::magickCell(paths = cell_data.new$images, return_single_imgs = T, cell_resize = 200)
```

# Load cell mask coords

From new -m option

```{r}
masks <- read_tsv("~/Software/cellID-linux/test_data_tmp/Position01/out_all_masks.tsv")

masks
```

```{r}
p <- ggplot(masks) + geom_tile(aes(x=xpos, y=ypos)) + facet_grid(flag~pixtype)

ggsave("masks.pdf", p, device = "pdf")

p
```

# Sin tframes

## Arguments setup

```{r}
path <- "/home/nicomic/Projects/Rdevel/rcell2/data/image_samples/"
# path <- "/home/nicomic/Projects/Rdevel/rcell2/data/time_series_image_samples/"
parameters <- "/home/nicomic/Software/cellID-linux/test_data_andy/Position001/parameters_vcellid_out.txt"

arguments <- rcell2::cellArgs2(path = path, parameters = parameters, 
                               file.pattern = "^(BF|[A-Z]FP)_Position(\\d+)().tif$")
arguments
```

## Run CellID

```{r}
rcell2::cell2(arguments = arguments, 
              cell.command = "~/Software/cellID-linux/cell", 
              dry = F, no_cores = 7)
```

