---
title: "rcell2 shinyCell app test"
author: "Nicolás Méndez"
date: "10/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Rebuild

```{r build, message=FALSE, warning=TRUE}
devtools::document()
devtools::load_all(recompile = F, reset = T, quiet = T)
# devtools::install(reload = T, build = F,
#                   quiet = T,
#                   upgrade = "never", keep_source = T)
# devtools::install_github("gerbeldo/rcell2", ref = "rcellid_no_labels")
# devtools::check()
# devtools::build()
# devtools::build(path="../../test_libtiff.tar.gz")
# remove.packages("rcell2")
# install.packages("../../test_libtiff.tar.gz", repos = NULL, type="source", clean = TRUE)
```

```{r setup, message=FALSE, warning=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# library(rcell2)

difference <- function(lista) abs(lista[1] - lista[2])
```

## Reinstall

```{r, eval=F}
devtools::install(reload = T, build = T,
                  quiet = T,
                  upgrade = "never", keep_source = T)
```

# Load paths

```{r}
path <- "data/time_series_image_samples/"
path.pdata <- paste0(path, "pdata.csv")
parameters <- "inst/parameters.txt"

pdata <- read_csv(path.pdata)
```

# USAGE

## Load data and plot something

```{r}
cell.data <- rcell2::cell.load.alt(path =  path, ucid.zero.pad = 5)

paths <- cell.data$images

# paths <- rcell2::magickPaths(cell.data)

cdata <- cell.data$data
```

## Basic usage

### Square tile

```{r}
cellMagick(cdata = cdata, paths = paths)
```

### 1D image types per ucid

```{r}
cdata.one.ucid <- cdata %>% filter(ucid == sample(cdata$ucid, 1))

cellGif(cdata.one.ucid, paths, channels = c("BF.out", "TFP.out"))

cellStrip(cdata.one.ucid, paths, channels = c("BF.out", "TFP.out"))
```

### 2D image tiles by variable:

```{r}
cellSpread(cdata, paths, ch = c("BF.out", "TFP.out"))

cellSpreadPlot(cdata, paths, ch = c("BF.out", "TFP.out"))

devtools::load_all(recompile = F, reset = T, quiet = T)
cellSpreadPlot(cdata, paths, ch = c("BF.out", "TFP.out"), overlay_points = T)
```

### Use in shinyApp

```{r}
shinyCell(left_join(cdata, pdata), pdata, paths, plotType = "Pics")
```


